### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Deeech** [wasche/ncss#4]
Hi! I writing [tool](https://deeech.github.io/css-minificator-tests/) for minifiers testing. It downloads several web sites, compresses them and does a screenshots to make sure that nothing been broken. And I get errors in some files.

`minified = ncss(source);`

`
RangeError: Maximum call stack size exceeded
    at _buffer (/home/deeech/Projects/git/css-minificator-tests/node_modules/ncss/lib/parser.js:65:19)
    at q (/home/deeech/Projects/git/css-minificator-tests/node_modules/ncss/lib/parser.js:81:12)
    at Object.handle [as token] (/home/deeech/Projects/git/css-minificator-tests/node_modules/ncss/lib/parser.js:215:9)
    at next (/home/deeech/Projects/git/css-minificator-tests/node_modules/ncss/lib/lexer.js:113:12)
    at num (/home/deeech/Projects/git/css-minificator-tests/node_modules/ncss/lib/lexer.js:74:7)
    at tokenize (/home/deeech/Projects/git/css-minificator-tests/node_modules/ncss/lib/lexer.js:138:7)
    at num (/home/deeech/Projects/git/css-minificator-tests/node_modules/ncss/lib/lexer.js:77:7)
    at tokenize (/home/deeech/Projects/git/css-minificator-tests/node_modules/ncss/lib/lexer.js:138:7)
    at num (/home/deeech/Projects/git/css-minificator-tests/node_modules/ncss/lib/lexer.js:77:7)
    at tokenize (/home/deeech/Projects/git/css-minificator-tests/node_modules/ncss/lib/lexer.js:138:7)
    at num (/home/deeech/Projects/git/css-minificator-tests/node_modules/ncss/lib/lexer.js:77:7)
    at tokenize (/home/deeech/Projects/git/css-minificator-tests/node_modules/ncss/lib/lexer.js:138:7)
    at num (/home/deeech/Projects/git/css-minificator-tests/node_modules/ncss/lib/lexer.js:77:7)
    at tokenize (/home/deeech/Projects/git/css-minificator-tests/node_modules/ncss/lib/lexer.js:138:7)
    at num (/home/deeech/Projects/git/css-minificator-tests/node_modules/ncss/lib/lexer.js:77:7)
    at tokenize (/home/deeech/Projects/git/css-minificator-tests/node_modules/ncss/lib/lexer.js:138:7)
    at num (/home/deeech/Projects/git/css-minificator-tests/node_modules/ncss/lib/lexer.js:77:7)
    at tokenize (/home/deeech/Projects/git/css-minificator-tests/node_modules/ncss/lib/lexer.js:138:7)
    at num (/home/deeech/Projects/git/css-minificator-tests/node_modules/ncss/lib/lexer.js:77:7)
    at tokenize (/home/deeech/Projects/git/css-minificator-tests/node_modules/ncss/lib/lexer.js:138:7)
    at num (/home/deeech/Projects/git/css-minificator-tests/node_modules/ncss/lib/lexer.js:77:7)
    at tokenize (/home/deeech/Projects/git/css-minificator-tests/node_modules/ncss/lib/lexer.js:138:7)`

Is this minifier error or I just don't use it correctly?

**Comment by wasche** [comment]
Regardless, it is a minifier error of some sort.
